<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=MetaHelper::getTitle();?></title>
</head>
<body>
<a href="/">Home</a>
<a href="/books">Books</a>
<a href="/contact-us">Contact</a>
<a href="/cart">Cart</a>
<?php if (Session::has('user')) : ?>
    <a href="/logout">Logout</a>
<?php else : ?>
    <a href="/login">Login</a>
<?php endif;?>
<hr>


<?=$content ?>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<hr>
All rights reserved &copy; 1980 - <?=date('Y')?>
</body>
</html>